### ISSUE TITLE
restart_file Path Gets Overwritten by the Default Value

### ISSUE THREAD

**Issue by vahid-dan** [FLARE-forecast/FCRE-forecast-code#2]
I need to change the `restart_file` path inside the `configure_run.yml` from `restart_file: /home/rstudio/FCRE-forecast-code/forecasts/fcre-2021-11-01-test_run.nc` to `restart_file: /root/FCRE-forecast-code/forecasts/fcre-2021-11-01-test_run.nc`. But it keeps changing it back to the default one.

**Comment by rqthomas** [comment]
This is because there is a restart file on the s3 bucket so it is pulling it in.  There are of options: delete the restart file in the bucket (which I would not do) or change the sim_name so it doesn't use the existing file on the s3 bucket.  The second is better and am putting in a pull request to fix this.  The PR will also include the two fixes in this PR so it isn't needed anymore.  BTW - it isn't a bug but a feature - just a feature that needed improvement.
